[WIP] Create a new ensimeFormatOnly task
ensime/ensime-sbt pull request #230
Opened 2016-10-19 20:32 UTC by yyadavalli

Need comments on the approach used. I had to create a Task similar to `ensimeCompileOnly` to get the source directories. 

I also need some pointer on how to write a test for this.

Solve #227

2016-10-19 20:47 UTC, fommil commented
@sugakandrey can you please help to review

2016-10-19 20:52 UTC, sugakandrey commented
I'll take a look.

2016-10-19 20:57 UTC, fommil commented
this looks great! As to tests, have you seen under the `src/sbt-tests` folder?

Basically create a project just for testing the formatting as per http://ensime.github.io/build_tools/sbt/#contributing which will link to the `scripted` documentation. It might be good to have a project with two `Project`s in it, each with different scalariform settings (possibly even different settings for `compile` vs `test` if that makes sense, but probably not) and then use the scripted command to assert that the sources match your expectations after running the `ensimeFormatOnly` and that it fails as expected. Maybe also try an `ensimeFormatOnly` without specifying the project (which should fail, but it would be nice if we could lookup the project/config to use... that may be too tricky)

Once this is merged, would you be up for updating some of the clients to use this command instead of talking to the server? This will definitely help us get to scala 2.12 sooner! (Speaking of which, we might need to pretend 2.12 is 2.11 when telling scalariform to format it).

2016-10-19 20:57 UTC, fommil requested changes

2016-10-19 20:57 UTC, fommil commented on src/main/scala/EnsimeExtrasPlugin.scala
> +                scalaVersion = version split "-" head
there may be a better way to obtain the scala version through sbt, this may break for some custom builds of scalac

2016-10-19 20:57 UTC, fommil commented on src/main/scala/EnsimeExtrasPlugin.scala
> +            val here = sourceDirs.exists { dir => input.getPath.startsWith(dir.getPath) }
it would be good to refactor this logic out into shared functionality with the `compileOnly` task

2016-10-19 21:04 UTC, yyadavalli commented on src/main/scala/EnsimeExtrasPlugin.scala
> +            val here = sourceDirs.exists { dir => input.getPath.startsWith(dir.getPath) }
I thought of that, just wanted to get an opinion on the approach before I did it

2016-10-19 21:05 UTC, yyadavalli commented on src/main/scala/EnsimeExtrasPlugin.scala
> +                scalaVersion = version split "-" head
I will look for that, just fyi, this is how it is done in `sbt-scalariform`

2016-10-19 21:08 UTC, yyadavalli commented
Regarding the tests, I did check under `sbt-tests`.
My only question is if I had a file named `Foo.scala` under sources and I formatted it won't that file be updated, Are the files reset after each run?

2016-10-19 21:09 UTC, fommil commented on src/main/scala/EnsimeExtrasPlugin.scala
> +                scalaVersion = version split "-" head
ok cool, then there is precedent. It's probably something like CrossVersion.partialVersion(scalaVersion)

2016-10-19 21:11 UTC, fommil commented
the entire project is copied to a temp location and then your scripted tests run. You might need to keep around a copy of each file in `src` in a `clean` and `formatted` form so that you can make assertions that it has or has not been mutated by the task.

2016-10-19 21:44 UTC, sugakandrey commented
Looks good to me, although I don't have much experience with sbt plugins.

2016-10-20 21:11 UTC, fommil reviewed
Cool! I'll look closer at the weekend when I'm at o computer. One thing occurred to me, it needs to be ensimeScalariformOnly because we plan on having a scalafmt variant at some point. I can do the emacs command.

2016-10-20 21:16 UTC, yyadavalli commented
Ok, I'll change the name.

2016-10-20 22:08 UTC, yyadavalli commented
Also, I'd like to try doing the emacs command with your help, it would help me get familiar with elisp.

2016-10-21 06:25 UTC, fommil commented
Ok! Have a look in the emacs command for compileOnly

2016-10-21 09:42 UTC, fommil commented
just thought of another use case, what about formatting files in the `project` directory? Perhaps use the root project's config?

2016-10-21 09:43 UTC, fommil commented
postfix ops warning on compile

2016-10-21 09:43 UTC, fommil commented
postfix ops warning on compile

2016-10-21 09:58 UTC, fommil commented
for emacs, see https://github.com/ensime/ensime-emacs/pull/476

2016-10-21 10:01 UTC, fommil commented
hmm, `ensime-sbt-find-subproject` seems to be broken for me at my work (Windows)... I'll investigate

2016-10-21 10:18 UTC, yyadavalli commented
Hmm, I did not see any postfix ops warnings. I looked over the CI builds too, did not find anything. Please point out if I am missing something.

I started looking into the emacs code I think I should move the following functions `ensime-rpc-format-buffer`, `ensime-rpc-async-format-files` and rework the `ensime-format-source` command. I'll open an issue in https://github.com/ensime/ensime-emacs we can continue there

2016-10-21 10:56 UTC, yyadavalli commented
@fommil when you are talking of formatting files in `project` directory, are you thinking of adding checks to this task to identify and pick settings appropriately?

2016-10-21 11:04 UTC, fommil commented
there won't be settings. Currently it fails.

2016-10-21 11:10 UTC, yyadavalli commented
Also, I don't think `project` folder shows up on the list of `sourceDirectories`

2016-10-21 11:37 UTC, fommil commented
yeah, exactly... it doesn't have a module name. So it'll be called without a module name. We might need to special case it.

2016-10-21 14:07 UTC, yyadavalli commented
I found a weird issue with this, for some reason `ensimeScalariformOnly` is running in all modules of a project when called in the root/default project
```
> ensimeCompileOnly a/src/main/scala/FormatMe.scala
[trace] Stack trace suppressed: run last format-only/compile:ensimeCompileOnly for the full output.
[error] (format-only/compile:ensimeCompileOnly) java.lang.IllegalArgumentException: a/src/main/scala/FormatMe.scala not associated to List(/home/yyadavalli/Developer/format-only/src/main/scala-2.10, /home/yyadavalli/Developer/format-only/src/main/scala, /home/yyadavalli/Developer/format-only/src/main/java, /home/yyadavalli/Developer/format-only/target/scala-2.10/src_managed/main)
[error] Total time: 0 s, completed Oct 21, 2016 10:06:04 AM
> ensimeScalariformOnly a/src/main/scala/FormatMe.scala
[info] Formatted /home/yyadavalli/Developer/format-only/a/src/main/scala/FormatMe.scala
[trace] Stack trace suppressed: run last format-only/compile:ensimeScalariformOnly for the full output.
[trace] Stack trace suppressed: run last b/compile:ensimeScalariformOnly for the full output.
[error] (format-only/compile:ensimeScalariformOnly) java.lang.IllegalArgumentException: a/src/main/scala/FormatMe.scala not associated to List(/home/yyadavalli/Developer/format-only/src/main/scala-2.10, /home/yyadavalli/Developer/format-only/src/main/scala, /home/yyadavalli/Developer/format-only/src/main/java, /home/yyadavalli/Developer/format-only/target/scala-2.10/src_managed/main)
[error] (b/compile:ensimeScalariformOnly) java.lang.IllegalArgumentException: a/src/main/scala/FormatMe.scala not associated to List(/home/yyadavalli/Developer/format-only/b/src/main/scala-2.10, /home/yyadavalli/Developer/format-only/b/src/main/scala, /home/yyadavalli/Developer/format-only/b/src/main/java, /home/yyadavalli/Developer/format-only/b/target/scala-2.10/src_managed/main)
[error] Total time: 0 s, completed Oct 21, 2016 10:06:26 AM
> 
```

2016-10-21 14:13 UTC, fommil commented
disable aggregation :wink:

2016-10-22 09:24 UTC, fommil commented
this is awesome! Thank you so much. I'll make a release later today after fixing a few more things. I think this deserves a minor number bump :smile:

2016-10-22 09:24 UTC, merged