testOnlyDebug command and changes in runMain and launchTask
ensime/ensime-sbt pull request #300
Opened 2017-01-20 11:37 UTC by vovapolu

2017-01-20 11:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ensime/ensime-sbt?pullRequest=300) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ensime/ensime-sbt?pullRequest=300) before we can accept your contribution.<br/>

2017-01-20 11:38 UTC, fommil commented
@dwijnand FYI

2017-01-20 11:42 UTC, dwijnand commented
Give thanks, men, to Leonidas and the brave #300! TO VICTORY!

2017-01-20 11:49 UTC, fommil commented
@vovapolu you could put some code in the sbt package, and expose what you need, no reflection needed

2017-06-21 21:52 UTC, fommil commented
btw, the tests failed on this due to a compiler warning (escalated to error in CI) and you haven't signed the CLA

2017-06-21 21:53 UTC, fommil commented on src/main/scala/SbtHelper.scala
> +  def consturctForkTests(runners: Map[TestFramework, Runner], tests: List[TestDefinition], config: Execution, classpath: Seq[File], fork: ForkOptions, log: Logger, tag: Tag): Task[TestOutput] = {
typo

2017-06-21 21:54 UTC, fommil commented on src/sbt-test/sbt-ensime/ensime-run-main/test
> +#> ensime-run-main/compile
lots of commented out tests?

2017-09-07 18:24 UTC, fommil commented
sweet, good to see it alive again :smile: I'll look tomorrow... brain fried from day at work

2017-09-07 18:26 UTC, fommil commented
we should remove the `debugging` mutating hack... I think it's in `EnsimePlugin.scala` if it's not in extras. This completes supercedes it.

2017-09-08 09:38 UTC, fommil approved these changes
ok, looks good! Let's remove the old debugging mechanism, merge this, and release with updated docs.

2017-09-10 18:41 UTC, fommil requested changes
great stuff, I think we can merge this once you remove the tests instead of just commenting them.

Would you like to practice your English by updating the docs? http://ensime.org/build_tools/sbt/#debugging-example If not, I will happily update them :smile:

2017-09-10 18:41 UTC, fommil commented on src/sbt-test/sbt-ensime/bad-build-scala/test
> +#> debugging
Remove instead of comment?

2017-09-11 21:04 UTC, fommil approved these changes

2017-09-11 21:05 UTC, fommil commented
I'll cut a new release tomorrow, and announce it when you've updated the docs. This will make a lot of people happy!

2017-09-12 07:15 UTC, merged