[WIP] Configuration logic for dependencies
ensime/ensime-sbt pull request #323
Opened 2017-04-26 22:43 UTC by yyadavalli

Resolve #247

2017-04-26 22:48 UTC, yyadavalli commented
@fommil please verify my changes in the tests. I have updated the `ensime-server` test, I am not sure I have it entirely correct. 
I am not clear on whether the same module with different config should be present or not. 
For example, with my change `server in compile` depends on `core in Compile, core in it, core in test`.  Please clarify.

2017-04-26 23:38 UTC, fommil commented
oh wow, totally out of the blue awesomeness :smile: it's bedtime here I'll have to review it in the morning. There is no "unread" button in github so if I forget, please ping me.

2017-04-27 16:36 UTC, fommil requested changes
the output looks good, so I think the logic is correct!

2017-04-27 16:36 UTC, fommil commented on src/main/scala/EnsimePlugin.scala
> +      val config = d.configuration.getOrElse("compile") match {
perhaps cleaner as `.get.collect { case IvyConfig(from, to) => to }.getOrElse("compile")`

2017-04-27 19:13 UTC, yyadavalli commented on src/main/scala/EnsimePlugin.scala
> +      val config = d.configuration.getOrElse("compile") match {
noob question, isn't it a bad idea call `.get` on a `Option` directly
How about
```scala
val config = d.configuration.map {
  case ivyConfig(from, to) => to
  case _ => "compile"
}.getOrElse("compile")
```

2017-04-27 19:43 UTC, fommil commented on src/main/scala/EnsimePlugin.scala
> +      val config = d.configuration.getOrElse("compile") match {
oh, I thought it was a `Map`. If it's an option already then just remove `.get`. And yes, you're right `collect` would drop the other case. Feels wrong to duplicate the `"compile"` but we can live with it. It's convention to use uppercase pattern matches though.

2017-04-27 19:44 UTC, fommil commented on src/main/scala/EnsimePlugin.scala
> +      val config = d.configuration.getOrElse("compile") match {
btw, `.collect` will turn the `case _` into a `None` and then the fallback will be used.

2017-04-27 19:50 UTC, yyadavalli commented on src/main/scala/EnsimePlugin.scala
> +      val config = d.configuration.getOrElse("compile") match {
Ok thanks, got it. I will update it

2017-04-27 20:55 UTC, fommil commented
you forgot to compile that :stuck_out_tongue: so the formatter got you

2017-04-27 23:05 UTC, yyadavalli commented
Cleaned and updated

2017-04-27 23:29 UTC, fommil commented
awesome, thank you so much this blocks the feature that I'm hoping our new sponsored student can work on!

2017-04-27 23:29 UTC, merged

2017-04-27 23:30 UTC, yyadavalli commented
Welcome, what is he planning to work on?